edit_model_name: "blip2-opt-2.7b"
edit_layer_inpt_path: "language_model.model.decoder.layers.30.fc1"
edit_layer_outpt_path: "language_model.model.decoder.layers.30.fc2"
edit_layer_i_of_inpt: 18
llm_layer_tmp: "language_model.model.decoder.layers"
llm_hidden_dim1: 2560
llm_hidden_dim2: 10240
lora_rank: 32
lora_edit_batch_size: 20
max_steps: 100
min_loss: 0.03
lr: 1.e-4
topk: 1