edit_model_name: blip2-opt-2.7b
counterfact_model_path: ".../opt-125m"
counterfact_model_rep_dim: 768
classifier_path: ".../bert-base-cased"
classifier_rep_dim: 768
llm_hidden_size: 2560
llm_norm_path: "language_model.model.decoder.final_layer_norm"
llm_voc_path: "language_model.lm_head"
train_config:
  lr: 1.e-4
  relia_lambda: 1
  gen_lambda: 1
  loc_lambda: 1
