edit_model_name: "blip2-opt-2.7b"
layers: [31]
num_steps: 25
batch_size: 1
lr: 1.e-3
weight_decay: 0
norm_constraint: false
rewrite_module_tmp: "language_model.model.decoder.layers.{}.fc2.weight" # last llm layer
# rewrite_module_tmp: "qformer" # vision module
